apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: devops-store
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: devops-store
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
