sonar.projectKey=devops-store-frontend
sonar.projectName=DevOps Store Frontend
sonar.sourceEncoding=UTF-8
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.spec.ts
sonar.exclusions=src/**/*.spec.ts
sonar.typescript.tsconfigPaths=tsconfig.app.json,tsconfig.spec.json
sonar.javascript.lcov.reportPaths=coverage/frontend/lcov.info
sonar.testExecutionReportPaths=sonar-report.xml
sonar.scanner.skipJreProvisioning=true
sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300
