CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    description VARCHAR(2000) NOT NULL DEFAULT '',
    category VARCHAR(30) NOT NULL,
    price NUMERIC(12, 2) NOT NULL,
    stock_quantity INTEGER NOT NULL,
    available BOOLEAN NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT chk_products_category CHECK (
        category IN ('SMARTPHONE', 'LAPTOP', 'TABLET', 'ACCESSORY', 'AUDIO', 'OTHER')
    ),
    CONSTRAINT chk_products_price CHECK (price >= 0),
    CONSTRAINT chk_products_stock_quantity CHECK (stock_quantity >= 0)
);

CREATE INDEX idx_products_name_lower ON products (LOWER(name));
CREATE INDEX idx_products_category ON products (category);
CREATE INDEX idx_products_available ON products (available);
