CREATE TABLE product_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES products (id) ON DELETE CASCADE,
    object_key VARCHAR(512) NOT NULL UNIQUE,
    content_type VARCHAR(50) NOT NULL,
    size_bytes BIGINT NOT NULL,
    width INTEGER NOT NULL,
    height INTEGER NOT NULL,
    position SMALLINT NOT NULL,
    is_primary BOOLEAN NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT chk_product_images_position CHECK (position BETWEEN 0 AND 4),
    CONSTRAINT ux_product_images_product_position UNIQUE (product_id, position)
);

CREATE UNIQUE INDEX ux_product_images_primary_per_product
    ON product_images (product_id)
    WHERE is_primary;
