apiVersion: v1
kind: ConfigMap
metadata:
  name: object-storage-config
  namespace: devops-store
  labels:
    app.kubernetes.io/name: object-storage
    app.kubernetes.io/part-of: devops-store
data:
  MINIO_ROOT_USER: devops_store
  HOME: /tmp
