# Exemple sans valeur reelle. Ne jamais committer de secret ni de licence.
# Creer les deux Secrets reels avec :
#   kubectl create secret generic object-storage-credentials -n devops-store `
#     --from-literal=MINIO_ROOT_PASSWORD=<meme valeur que MINIO_SECRET_KEY>
#   kubectl create secret generic object-storage-license -n devops-store `
#     --from-file=minio.license=$env:MINIO_LICENSE_FILE
apiVersion: v1
kind: Secret
metadata:
  name: object-storage-credentials
  namespace: devops-store
  labels:
    app.kubernetes.io/name: object-storage
    app.kubernetes.io/part-of: devops-store
type: Opaque
stringData:
  MINIO_ROOT_PASSWORD: ""
